/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofuncionario.view;

import com.mycompany.projetofuncionario.control.OperacoesFuncionario;
import com.mycompany.projetofuncionario.model.Funcionario;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class CadastraFuncionario extends javax.swing.JFrame {

    private Principal principal;
    private int posicaoCombo;
    private Funcionario funcionarioParaEdicao;
    private TextosDeTela textosDeTela = new TextosDeTela();
    
    /**
     * 
     */
    public void init() {
        lbTituloCadFuncionario.setText(textosDeTela.funcionario);
        lbNomeCadFuncionario.setText(textosDeTela.funcionarioNome);
        lbDataAniversarioCadFuncionario
                .setText(textosDeTela.funcionarioDataNascimento);
        lbSalarioCadFuncionario.setText(textosDeTela.funcionarioSalario);
        lbFuncaoCadFuncionario.setText(textosDeTela.funcionarioFuncao);

        btnOk.setText(textosDeTela.ok);
        btnCancelar.setText(textosDeTela.cancelar);
    }

    public CadastraFuncionario() {
        initComponents();
        init();
    }

    /**
     * Creates new form CadastraFuncionario
     */
    public CadastraFuncionario(Principal principal, int posicaoCombo) {
        this();
        this.principal = principal;
        this.posicaoCombo = posicaoCombo;
    }

    public CadastraFuncionario(Principal principal, int posicaoCombo,
            Funcionario funcionario) {
        this();
        this.principal = principal;
        this.posicaoCombo = posicaoCombo;
        this.funcionarioParaEdicao = funcionario;

        insereDadosFuncionarioParaEdicao(funcionario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNomeCadFuncionario = new javax.swing.JLabel();
        nomeFuncionario = new javax.swing.JTextField();
        lbFuncaoCadFuncionario = new javax.swing.JLabel();
        funcaoFuncionario = new javax.swing.JTextField();
        dataAniversarioFuncionario = new javax.swing.JFormattedTextField();
        lbDataAniversarioCadFuncionario = new javax.swing.JLabel();
        lbSalarioCadFuncionario = new javax.swing.JLabel();
        salarioFuncionario = new javax.swing.JFormattedTextField();
        lbTituloCadFuncionario = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funcionário");

        lbNomeCadFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNomeCadFuncionario.setText("lbNomeCadFuncionario");

        lbFuncaoCadFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbFuncaoCadFuncionario.setText("lbFuncaoCadFuncionario");

        dataAniversarioFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        lbDataAniversarioCadFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDataAniversarioCadFuncionario.setText("lbDataAniversarioCadFuncionario");

        lbSalarioCadFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSalarioCadFuncionario.setText("lbSalarioCadFuncionario");

        salarioFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        lbTituloCadFuncionario.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lbTituloCadFuncionario.setText("lbTituloCadFuncionario");

        btnOk.setText("jButton1");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("jButton2");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbNomeCadFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeFuncionario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbDataAniversarioCadFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataAniversarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbTituloCadFuncionario)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbSalarioCadFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbFuncaoCadFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(funcaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 76, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloCadFuncionario)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomeCadFuncionario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataAniversarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataAniversarioCadFuncionario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSalarioCadFuncionario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funcaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFuncaoCadFuncionario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        if (nomeFuncionario.getText().trim() != null
                && dataAniversarioFuncionario.getText().trim() != null
                && salarioFuncionario.getText().trim() != null
                && funcaoFuncionario.getText().trim() != null) {
            DateTimeFormatter formatData
                    = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            LocalDate dataAniversario
                    = LocalDate.parse(dataAniversarioFuncionario.getText(),
                            formatData);

            BigDecimal salario
                    = new BigDecimal(salarioFuncionario.getText()
                            .replace(".", "").replace(",", "."));

            OperacoesFuncionario operacoesFuncionario
                    = new OperacoesFuncionario();

            if (funcionarioParaEdicao == null) {
                Funcionario funcionario
                        = operacoesFuncionario.insereFuncionario(
                                nomeFuncionario.getText(),
                                dataAniversario,
                                salario,
                                funcaoFuncionario.getText());

                principal.listaFuncionarios.add(funcionario);
            } else {
                operacoesFuncionario.atualizaFuncionario(funcionarioParaEdicao,
                        nomeFuncionario.getText(),
                        dataAniversario,
                        salario,
                        funcaoFuncionario.getText());
            }

            principal.LoadTabelaFuncionario(posicaoCombo);
            fechaTela();
        } else {
            JOptionPane.showMessageDialog(this,
                    textosDeTela.validacaoCamposFuncionario);
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        fechaTela();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void fechaTela() {
        this.dispose();
        principal.setVisible(true);
    }

    private void insereDadosFuncionarioParaEdicao(Funcionario funcionario) {
        String format = "#,##0.00";
        NumberFormat formatSalario = new DecimalFormat(format);
        String salario = formatSalario.format(
                            funcionario.getSalario().doubleValue());

        nomeFuncionario.setText(funcionario.getNome());
        dataAniversarioFuncionario.setText(funcionario.getDataNascimento()
                .format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        salarioFuncionario.setText(salario);
        funcaoFuncionario.setText(funcionario.getFuncao());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JFormattedTextField dataAniversarioFuncionario;
    private javax.swing.JTextField funcaoFuncionario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDataAniversarioCadFuncionario;
    private javax.swing.JLabel lbFuncaoCadFuncionario;
    private javax.swing.JLabel lbNomeCadFuncionario;
    private javax.swing.JLabel lbSalarioCadFuncionario;
    private javax.swing.JLabel lbTituloCadFuncionario;
    private javax.swing.JTextField nomeFuncionario;
    private javax.swing.JFormattedTextField salarioFuncionario;
    // End of variables declaration//GEN-END:variables
}
